name: rx_notifier_generator
description: Generate RxNotifier getter and setter. Use annotations @store and @rx
version: 1.0.1
homepage: https://github.com/Flutterando/rxnotifier

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  build: '>=2.3.1 <3.0.0'
  source_gen: '>=1.2.7 <2.0.0'
  analyzer: '>=5.6.0 <6.0.0'
  rx_notifier_annotation: ">=1.0.0 <2.0.0"

dev_dependencies:
  build_test: '>=2.1.6 <3.0.0'
  build_runner: '>=2.4.0 <3.0.0'
  test: '>=1.23.1 <2.0.0'